# Default values for ms-orders.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: registy.btcbolsa.host
  tag: dev
  pullPolicy: IfNotPresent

env:
  REDIS_HOST: redis-pro-master

envBySecret:
  - name: REDIS_PASS
    secret: redis-pro
    key: redis-password

envFromSecret:
  - ms-common
  - sendgrid

apmEnable: true

resources:
  limits:
    cpu: 100m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 50
  targetCPUUtilizationPercentage: 85
  targetMemoryUtilizationPercentage: 85


internalPort: 3000

enableProbe: true
probePath: /health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10